name: Build Quasar RAT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      run: nuget restore Quasar.sln

    - name: Build Solution (Release)
      run: msbuild Quasar.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Quasar-Binaries
        path: |
          Quasar.Client/bin/Release/
          Quasar.Server/bin/Release/
        if-no-files-found: error
