name: Build Quasar

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore Quasar.sln

      - name: Build solution (Release)
        run: msbuild Quasar.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Quasar-Build
          path: Bin/
