name: Build Quasar RAT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级至v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - name: Restore NuGet Packages
      run: nuget restore Quasar.sln

    - name: Build Solution (Release)
      run: msbuild Quasar.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4  # 升级至v4
      with:
        name: Quasar-Binaries
        path: |
          Quasar.Client/bin/Release/
          Quasar.Server/bin/Release/
        if-no-files-found: error
