name: Quasar CI

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true  # 禁用首次运行优化

    steps:
    - uses: actions/checkout@v4

    - name: Cache NuGet
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          ​**/packages.config
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: 17.0

    - name: Restore Packages
      run: |
        nuget restore Quasar.sln -ForceEvaluate  # 强制重新生成assets文件
        if ($LASTEXITCODE -ne 0) { exit 1 }

    - name: Build Solution
      run: |
        msbuild Quasar.sln 
          /p:Configuration=Release 
          /p:Platform="AnyCPU" 
          /p:RestorePackages=false  # 禁用构建时的自动恢复
          /p:TargetFrameworkVersion=v4.5.2  # 显式指定框架版本
